# SPDX-License-Identifier: AGPL-3.0-or-later
github: anulum
buy_me_a_coffee: anulum
custom:
  - "https://www.anulum.li/licensing"
  - "https://www.paypal.com/donate?hosted_button_id=4X5F6DNT934HY"
  - "https://go.twint.ch/1/e/tw?tw=acq.lJTAypb8SL2s8vPg7fL0ubi2C220ajOH0BEQn1aKfEJIiIakLpt8jlEv8XdQ9tCp."
