# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SYNAPSE_CHANNEL — changelog and release-note claim hygiene regressions

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CHECKER = REPO_ROOT / "tools" / "check_release_claim_hygiene.py"
CHANGELOG = REPO_ROOT / "CHANGELOG.md"


def _run_checker(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECKER), *args],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )


def test_release_claim_hygiene_passes_current_changelog() -> None:
    result = _run_checker("--check")

    assert result.returncode == 0, result.stderr + result.stdout
    assert "release claim hygiene passed" in result.stdout


def test_release_claim_hygiene_detects_agent_authorship_claim(tmp_path: Path) -> None:
    drifted = tmp_path / "CHANGELOG.md"
    drifted.write_text(
        CHANGELOG.read_text(encoding="utf-8")
        + "\n## Bad\n\n- Generated by Codex as production-grade output.\n",
        encoding="utf-8",
    )

    result = _run_checker("--check", "--path", str(drifted))

    assert result.returncode == 1
    assert "agent-authorship" in result.stderr
    assert "quality-label" in result.stderr


def test_release_claim_hygiene_detects_certification_overclaim(tmp_path: Path) -> None:
    drifted = tmp_path / "CHANGELOG.md"
    drifted.write_text(
        CHANGELOG.read_text(encoding="utf-8")
        + "\n## Bad\n\n- The bridge is officially certified for full A2A conformance.\n",
        encoding="utf-8",
    )

    result = _run_checker("--check", "--path", str(drifted))

    assert result.returncode == 1
    assert "conformance-overclaim" in result.stderr
