# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SYNAPSE_CHANNEL — scaffold for a runnable coding-fleet demo workspace
"""Create the files behind ``synapse new coding-fleet``."""

from __future__ import annotations

from pathlib import Path

TEMPLATE_MARKER = "<!-- synapse-coding-fleet-template -->"
"""Marker identifying files generated by the coding-fleet scaffold."""

DEFAULT_WORKSPACE = "synapse-coding-fleet"
"""Default workspace directory created by ``synapse new coding-fleet``."""


def _readme_body() -> str:
    """Return the generated workspace README."""
    return f"""# Synapse coding fleet demo

{TEMPLATE_MARKER}

This workspace is generated by `synapse new coding-fleet`. It demonstrates two
coding agents coordinating on one repository without editing the same file.

## Run

```bash
python -m pip install synapse-channel
python run_demo.py
```

The demo starts its own local hub, runs `api-dev` and `test-dev`, proves an
overlapping file claim is refused, proves a disjoint test claim is granted, and
then tears the hub down. It succeeds when it prints:

```text
success: coding fleet demo completed
```

## Files

- `run_demo.py` runs the installed packaged demo runtime.
- `src/app/api.py` is the source path `api-dev` claims.
- `tests/test_api.py` is the test path `test-dev` claims.
- `.synapse/project` gives the workspace a stable project name for later manual
  experiments with `synapse git-init`, `synapse board`, and `synapse doctor`.
"""


def _run_demo_body() -> str:
    """Return the generated ``run_demo.py`` script body."""
    return '''# SPDX-License-Identifier: AGPL-3.0-or-later
"""Run the generated Synapse coding-fleet demo workspace."""

from __future__ import annotations

from synapse_channel.coding_fleet import main


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _api_body() -> str:
    """Return the placeholder API source used by the generated demo."""
    return '''"""Tiny API module used by the Synapse coding-fleet demo."""

from __future__ import annotations


def status() -> str:
    """Return a deterministic status used by the demo test file."""
    return "ready"
'''


def _test_body() -> str:
    """Return the placeholder test source used by the generated demo."""
    return '''"""Tiny test module used by the Synapse coding-fleet demo."""

from __future__ import annotations

from src.app.api import status


def test_status() -> None:
    """The generated API starts in a known ready state."""
    assert status() == "ready"
'''


def _write(path: Path, body: str) -> None:
    """Write ``body`` to ``path``, creating parent directories."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")


def create_coding_fleet(path: Path, *, force: bool = False) -> list[str]:
    """Create a runnable coding-fleet demo workspace.

    Parameters
    ----------
    path : Path
        Target workspace directory.
    force : bool, optional
        When ``False``, a non-empty existing directory is refused. When ``True``,
        generated template files are written or refreshed, but unrelated files are
        left untouched.

    Returns
    -------
    list[str]
        Human-readable next-step lines for the CLI.

    Raises
    ------
    FileExistsError
        If ``path`` exists, is non-empty, and ``force`` is ``False``.
    """
    target = path.expanduser()
    if target.exists() and any(target.iterdir()) and not force:
        raise FileExistsError(f"{target} is not empty; pass --force to refresh template files")
    target.mkdir(parents=True, exist_ok=True)

    files = {
        "README.md": _readme_body(),
        "run_demo.py": _run_demo_body(),
        "src/app/api.py": _api_body(),
        "tests/test_api.py": _test_body(),
        ".synapse/project": "coding-fleet\n",
    }
    for relative, body in files.items():
        _write(target / relative, body)

    return [
        f"created coding fleet workspace: {target}",
        f"next: cd {target}",
        "next: python -m pip install synapse-channel",
        "next: python run_demo.py",
    ]
