# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SYNAPSE_CHANNEL — dashboard bind validation and HTTP bearer-token resolution
"""Bind-address and bearer-token policy for the dashboard HTTP server.

The dashboard defaults to a loopback-only, read-only observer. Two decisions guard
its exposure, kept here as one small responsibility so the server module does not
carry them: whether a bind host may be served at all (:func:`validate_dashboard_bind`)
and what bearer token, if any, gates its HTTP requests (:func:`_resolve_dashboard_token`).
The token policy is security-critical — an armed operator write-path must never be
reachable unauthenticated, even on loopback — so it lives in its own testable unit.
"""

from __future__ import annotations

import contextlib
import ipaddress
import secrets
from typing import Final

LOOPBACK_HOSTS: Final[frozenset[str]] = frozenset({"localhost", "127.0.0.1", "::1"})


def _is_loopback_host(host: str) -> bool:
    """Return whether ``host`` names a loopback-only bind target."""
    candidate = host.strip().lower()
    if candidate in LOOPBACK_HOSTS:
        return True
    with contextlib.suppress(ValueError):
        return ipaddress.ip_address(candidate).is_loopback
    return False


def validate_dashboard_bind(host: str, *, allow_non_loopback: bool) -> None:
    """Refuse non-loopback dashboard binds unless explicitly allowed.

    Parameters
    ----------
    host : str
        Host literal or name passed to the dashboard HTTP server.
    allow_non_loopback : bool
        Whether the caller explicitly accepts exposing the read-only dashboard
        beyond loopback.

    Raises
    ------
    ValueError
        If ``host`` is not a loopback target and ``allow_non_loopback`` is false.
    """
    if allow_non_loopback or _is_loopback_host(host):
        return
    raise ValueError(
        "dashboard binds to loopback by default; pass --allow-non-loopback "
        "only behind trusted local network controls"
    )


def _resolve_dashboard_token(
    host: str,
    *,
    allow_non_loopback: bool,
    dashboard_token: str | None,
    operator: bool,
) -> tuple[str | None, bool]:
    """Return the effective dashboard HTTP bearer token.

    Parameters
    ----------
    host : str
        HTTP bind host supplied by the operator.
    allow_non_loopback : bool
        Whether the operator explicitly allowed an exposed dashboard bind.
    dashboard_token : str or None
        Caller-provided dashboard HTTP bearer token.
    operator : bool
        Whether the operator write-path is armed. When it is, a token is required
        even on loopback: an unauthenticated write endpoint is a same-host
        cross-process (local CSRF) write risk, so a token is generated if the caller
        supplied none. A read-only loopback dashboard needs no token.

    Returns
    -------
    tuple[str or None, bool]
        Effective bearer token and whether it was generated by the server.

    Raises
    ------
    ValueError
        If the caller supplied an empty dashboard token.
    """
    if dashboard_token is not None and len(dashboard_token) == 0:
        raise ValueError("dashboard token must not be empty")
    if dashboard_token is not None:
        return dashboard_token, False
    # Generate a token when the write-path is armed (even on loopback) or the bind is
    # exposed — either way an unauthenticated request could act, so it must not.
    if operator or (allow_non_loopback and not _is_loopback_host(host)):
        return secrets.token_urlsafe(32), True
    return None, False
