name: clients-js

on:
  push:
    paths:
      - "clients/js/**"
      - ".github/workflows/clients-js.yml"
  pull_request:
    paths:
      - "clients/js/**"
      - ".github/workflows/clients-js.yml"

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/js
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: clients/js/package-lock.json
      - run: npm ci
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
